name: Unit test and build compiled components

on:  [push, pull_request]

jobs:

  build-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.3'
        cache-dependency-path: frontend-tui/go.sum

    - name: Test
      run: |
        cd frontend-tui
        go test -v
        
    - name: Build
      run: |
        cd frontend-tui
        export GOARCH=amd64
        export CGO_ENABLED=0
        go build -v -ldflags="-s -w" -o opinionated-installer

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: opinionated-installer
        path: frontend-tui/opinionated-installer

  build-web-gui:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'

    - name: Build
      run: |
        cd frontend
        npm ci
        npm run build
        
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: browser-gui-frontend-dist
        path: frontend/dist/
