# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Text User Interface Frontend

on:  [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache-dependency-path: frontend-tui/go.sum

    - name: Build
      run: |
        cd frontend-tui
        export GOARCH=amd64
        export CGO_ENABLED=0
        go build -v -ldflags="-s -w" -o opinionated-installer-tui

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: built-binary
        path: frontend-tui/opinionated-installer-tui
