name: Build and Package Installer

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        if: ${{ hashFiles('frontend/package.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Build frontend
        if: ${{ hashFiles('frontend/package.json') != '' }}
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Set up Go
        if: ${{ hashFiles('frontend-tui/go.mod') != '' }}
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache-dependency-path: frontend-tui/go.sum

      - name: Build backend
        if: ${{ hashFiles('frontend-tui/go.mod') != '' }}
        run: |
          cd frontend-tui
          export CGO_ENABLED=0
          go build -v -ldflags="-s -w" -o opinionated-installer

      - name: Package bundle
        run: |
          bash packaging/create_release_tar.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: opinionated-debian-installer
          path: |
            dist/opinionated-debian-installer.tar.gz
            dist/SHA256SUMS

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/opinionated-debian-installer.tar.gz
            dist/SHA256SUMS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
